---
- name: "Install Glances"
  notify:
    - "Enable and start Glances"
    - "Restart Glances"
  block:
    - name: "Install Python packages"
      ansible.builtin.package:
        update_cache: true
        name:
          - "python3"
          - "python3-jmespath"
          - "python3-pip"

    - name: "Set PIP_BREAK_SYSTEM_PACKAGES var"
      register: output
      changed_when: output.rc != 0
      ansible.builtin.command: |
        export PIP_BREAK_SYSTEM_PACKAGES=1

    - name: "Install Glances packages with PIP"
      ansible.builtin.pip:
        name:
          - "bottle"
          - "glances"

    - name: Import glances.service conf
      ansible.builtin.template:
        src: "templates/glances.service.j2"
        dest: "/etc/systemd/system/glances.service"
        mode: "0600"
        group: "root"
        owner: "root"
