---
- name: "Install Python packages"
  ansible.builtin.package:
    update_cache: yes
    name:
      - python3
      - python3-jmespath
      - python3-pip

- name: "Install Glances packages with PIP"
  ansible.builtin.pip:
    name:
      - bottle
      - glances

- name: Import glances.service conf
  notify: "Enable and start Glances"
  ansible.builtin.template:
    src: "templates/glances.service.j2"
    dest: "/etc/systemd/system/glances.service"
    mode: 0700
