---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.install_glances"
      tags:
        - "labocbz.install_glances"
      vars:
        install_glances__refresh_time: "{{ inv_install_glances__refresh_time }}"
        install_glances__port: "{{ inv_install_glances__port }}"
      ansible.builtin.include_role:
        name: "labocbz.install_glances"
