---
- name: "Enable and start Glances"
  register: install_glances__service_status
  changed_when: install_glances__service_status.state != "started"
  ansible.builtin.service:
    name: "glances"
    state: "started"
    enabled: yes
    daemon_reload: true

- name: "Restart Glances"
  register: install_glances__service_status
  changed_when: install_glances__service_status.state != "restarted"
  ansible.builtin.service:
    name: "glances"
    state: "started"
    enabled: yes
    daemon_reload: true
