---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "all"
  gather_facts: false
  tasks:

    - name: "Get Glances service current state"
      register: glances_service_status
      failed_when: not glances_service_status.status.ActiveState == 'active'
      ansible.builtin.systemd:
        name: "glances"

    - name: "Check Glances connectivity"
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ inv_glances_port }}"
        timeout: 120
